# Generated by Django 5.0.7 on 2024-07-10 12:11

import django.utils.timezone
import regist.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='user_images/', validators=[regist.validators.image_validator]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=32, validators=[regist.validators.password_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[regist.validators.username_validator]),
        ),
    ]
